### ISSUE TITLE
Not Rendering in Game or Scene View

### ISSUE THREAD

**Issue by DonnerTech** [alexmalyutindev/unity-urp-radiance-cascades#1]
![Screenshot 2024-12-02 174440](https://github.com/user-attachments/assets/b06411b3-e85c-4fd8-88ed-054bd6e4eab6)

I've tried this with new and old versions of this project. How do I see the render output correctly? In the image you can see that some of the code is working in the margins of the inspector but there is clearly something wrong.

**Comment by alexmalyutindev** [comment]
@DonnerTech Wow, this is really strange behaviour of the feature, something unexpected happened.
I've tested feature only on MacOS and it works correct, I need to check it on Windows.
I believe, smth went wrong with Blit function.

For better understanding, can you provide your pc specs?

**Comment by alexmalyutindev** [comment]
@DonnerTech Found out that render pass attachments was messed up on Windows, looks like URP's Deferred pass bug 🫠
Forced set correct ones, should works.

Can you please check the last commit on master branch?

**Comment by DonnerTech** [comment]
On it.

**Comment by DonnerTech** [comment]
![Screenshot 2024-12-02 235348](https://github.com/user-attachments/assets/893d2b3e-207b-4589-a2df-19f714f4b30d)
![Screenshot 2024-12-02 235505](https://github.com/user-attachments/assets/57ab0ca1-2d3a-47b2-9014-38dda27e05b7)

Appears to be working smoothly now! Great job and thank you.
